# Basic
title: Nutshell
subtitle: 
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 记录开发与生活的点滴小事
# creator: <a href="http://onev.cat">@onevcat</a>

# url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
#    - {title: Projects, description: My Projects, url: 'https://github.com/dutchmanxj'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    #weibo: onevcat
    github: dutchmanxj
    twitter: Lawrencexu_
    # gplus: 107108267983477358170
    mail: lawrencexu918@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

exclude: [vendor]
timezone: Asia/Shanghai
